language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install numpy
  - pip install pandas
  - pip install scipy
  - pip install matplotlib
  - pip install sklearn
  - pip install .

# command to run tests
script:
  - pytest
